version: '3.8'

services:
  dbservice:
    image: postgres:16.2
    container_name: postgresdb
    environment:
      POSTGRES_DB: avs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress!209206
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - avs-network

  appservice:
    image: captainambar/avs-security:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - dbservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/avs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgress!209206
    networks:
      - avs-network

volumes:
  postgres-data:

networks:
  avs-network:
